version: 1.0.{build}
skip_branch_with_pr: true
image: Visual Studio 2019
environment:
  WEBHOOK_URL:
    secure: gOKbXaZM9ImtMD5XrYITvdyZUW/az082G9OIN1EC1Vbg57wBaeLhi49uGjxPw5GVujHku6kxN6ab89zhbS5GVeluR76GM83IbKV4Sh7udXzoYZZdg6YudtYHzdhCgUeiedpswbuczTq9ceIkkfSEWZuh/lMAAVVwvcGsJAnoPFw=
build_script:
- pwsh: >-
    $ErrorActionPreference = 'Stop'

    git clone --depth=1 --no-single-branch https://github.com/ModOrganizer2/modorganizer-umbrella.git c:\projects\modorganizer-umbrella

    New-Item -ItemType Directory -Path c:\projects\modorganizer-build

    cd c:\projects\modorganizer-umbrella
    
    ($env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH -eq $null) ? ($branch = $env:APPVEYOR_REPO_BRANCH) : ($branch = $env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH)

    git checkout $(git show-ref --verify --quiet refs/remotes/origin/${branch} || echo '-b') ${branch}

    C:\Python37-x64\python.exe unimake.py -d c:\projects\modorganizer-build -s Appveyor_Build=True ${env:APPVEYOR_PROJECT_NAME}
    
    if($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode )  }
artifacts:
- path: vsbuild\src\RelWithDebInfo\game_fallout4.dll
  name: game_fallout4_dll
- path: vsbuild\src\RelWithDebInfo\game_fallout4.pdb
  name: game_fallout4_pdb
- path: vsbuild\src\RelWithDebInfo\game_fallout4.lib
  name: game_fallout4_lib
on_success:
  - ps: Set-Location -Path $env:APPVEYOR_BUILD_FOLDER
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Set-Location -Path $env:APPVEYOR_BUILD_FOLDER
  - ps: Push-AppveyorArtifact ${env:APPVEYOR_BUILD_FOLDER}\stdout.log
  - ps: Push-AppveyorArtifact ${env:APPVEYOR_BUILD_FOLDER}\stderr.log
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL